/* Star City Drift service worker — GENERATED by tools/build-app.mjs. Do not edit by hand. */
const VERSION = '66e5f78bad2b';
const CACHE_PREFIX = 'star-city-drift-';
const CACHE = CACHE_PREFIX + VERSION;
const PRECACHE = [
  "./",
  "assets/bg/community.png",
  "assets/bg/community_v1.png",
  "assets/bg/diner.png",
  "assets/bg/diner_v1.png",
  "assets/bg/downtown.png",
  "assets/bg/downtown_golden.png",
  "assets/bg/downtown_v1.png",
  "assets/bg/gym.png",
  "assets/bg/gym_v1.png",
  "assets/bg/millmountain.png",
  "assets/bg/millmountain_v1.png",
  "assets/bg/pages.png",
  "assets/bg/pages_v1.png",
  "assets/bg/rails.png",
  "assets/bg/railyard.png",
  "assets/bg/railyard_v1.png",
  "assets/bg/river.png",
  "assets/bg/river_v1.png",
  "assets/bg/skate.png",
  "assets/bg/skate_v1.png",
  "assets/bg/star.png",
  "assets/props/bench.png",
  "assets/props/sedan_rear.png",
  "assets/props/sedan_side.png",
  "assets/props/trashcan.png",
  "assets/sprites/anims.json",
  "assets/sprites/anims_enemies.json",
  "assets/sprites/cam.png",
  "assets/sprites/cam_anim.png",
  "assets/sprites/cam_sheet.png",
  "assets/sprites/cam_v1.png",
  "assets/sprites/coach.png",
  "assets/sprites/coach_anim.png",
  "assets/sprites/coach_anim_wide.png",
  "assets/sprites/coach_sheet.png",
  "assets/sprites/coach_v1.png",
  "assets/sprites/collectibles.json",
  "assets/sprites/collectibles.png",
  "assets/sprites/dee.png",
  "assets/sprites/dee_anim.png",
  "assets/sprites/dee_sheet.png",
  "assets/sprites/dee_v1.png",
  "assets/sprites/fx.png",
  "assets/sprites/hank.png",
  "assets/sprites/hank_anim.png",
  "assets/sprites/hank_sheet.png",
  "assets/sprites/hank_v1.png",
  "assets/sprites/heart.png",
  "assets/sprites/heart_empty.png",
  "assets/sprites/heart_empty_v1.png",
  "assets/sprites/heart_v1.png",
  "assets/sprites/june.png",
  "assets/sprites/june_anim.png",
  "assets/sprites/june_sheet.png",
  "assets/sprites/june_v1.png",
  "assets/sprites/matthew.png",
  "assets/sprites/matthew_beacon.png",
  "assets/sprites/matthew_beacon_anim.png",
  "assets/sprites/matthew_beacon_anim_wide.png",
  "assets/sprites/matthew_diner.png",
  "assets/sprites/matthew_diner_anim.png",
  "assets/sprites/matthew_diner_anim_wide.png",
  "assets/sprites/matthew_gold.png",
  "assets/sprites/matthew_gold_anim.png",
  "assets/sprites/matthew_gold_anim_wide.png",
  "assets/sprites/matthew_hoodie.png",
  "assets/sprites/matthew_hoodie_anim.png",
  "assets/sprites/matthew_hoodie_anim_wide.png",
  "assets/sprites/matthew_idle.png",
  "assets/sprites/matthew_jacket.png",
  "assets/sprites/matthew_jacket_anim.png",
  "assets/sprites/matthew_jacket_anim_wide.png",
  "assets/sprites/matthew_mechanic.png",
  "assets/sprites/matthew_mechanic_anim.png",
  "assets/sprites/matthew_mechanic_anim_wide.png",
  "assets/sprites/matthew_photo.png",
  "assets/sprites/matthew_photo_anim.png",
  "assets/sprites/matthew_photo_anim_wide.png",
  "assets/sprites/matthew_polo_anim.png",
  "assets/sprites/matthew_polo_anim_wide.png",
  "assets/sprites/matthew_sheet.png",
  "assets/sprites/matthew_sheet_v1.png",
  "assets/sprites/matthew_sheet_v2.png",
  "assets/sprites/matthew_street.png",
  "assets/sprites/matthew_street_anim.png",
  "assets/sprites/matthew_street_anim_wide.png",
  "assets/sprites/matthew_varsity.png",
  "assets/sprites/matthew_varsity_anim.png",
  "assets/sprites/matthew_varsity_anim_wide.png",
  "assets/sprites/matthew_webslinger.png",
  "assets/sprites/matthew_webslinger_anim.png",
  "assets/sprites/matthew_webslinger_anim_wide.png",
  "assets/sprites/npcs.png",
  "assets/sprites/npcs_v1.png",
  "assets/sprites/portrait_matthew.png",
  "assets/sprites/portrait_matthew_v3_side.png",
  "assets/sprites/priya.png",
  "assets/sprites/priya_anim.png",
  "assets/sprites/priya_sheet.png",
  "assets/sprites/priya_v1.png",
  "assets/sprites/silas.png",
  "assets/sprites/silas_anim.png",
  "assets/sprites/silas_boss_anim.png",
  "assets/sprites/silas_boss_anim_wide.png",
  "assets/sprites/silas_sheet.png",
  "assets/sprites/silas_v1.png",
  "assets/sprites/snatcher.png",
  "assets/sprites/snatcher_anim.png",
  "assets/sprites/snatcher_anim_wide.png",
  "assets/sprites/tessa.png",
  "assets/sprites/tessa_anim.png",
  "assets/sprites/tessa_sheet.png",
  "assets/sprites/tessa_v1.png",
  "assets/sprites/thug_grey.png",
  "assets/sprites/thug_grey_anim.png",
  "assets/sprites/thug_grey_anim_wide.png",
  "assets/sprites/thug_grey_sheet.png",
  "assets/sprites/thug_orange.png",
  "assets/sprites/thug_orange_anim.png",
  "assets/sprites/thug_orange_anim_wide.png",
  "assets/sprites/thug_orange_sheet.png",
  "assets/sprites/thug_purple.png",
  "assets/sprites/thug_purple_anim.png",
  "assets/sprites/thug_purple_anim_wide.png",
  "assets/sprites/thug_purple_sheet.png",
  "assets/sprites/thug_purple_v1.png",
  "assets/sprites/thug_red.png",
  "assets/sprites/thug_red_anim.png",
  "assets/sprites/thug_red_anim_wide.png",
  "assets/sprites/thug_red_sheet.png",
  "assets/sprites/thug_red_v1.png",
  "assets/sprites/thug_teal.png",
  "assets/sprites/thug_teal_anim.png",
  "assets/sprites/thug_teal_anim_wide.png",
  "assets/sprites/thug_teal_sheet.png",
  "assets/sprites/thug_teal_v1.png",
  "assets/sprites/wren.png",
  "assets/sprites/wren_anim.png",
  "assets/sprites/wren_sheet.png",
  "css/style.css",
  "icons/apple-touch-icon.png",
  "icons/favicon-32.png",
  "icons/favicon.ico",
  "icons/icon-1024.png",
  "icons/icon-192.png",
  "icons/icon-512.png",
  "icons/icon-maskable-1024.png",
  "icons/icon-maskable-192.png",
  "icons/icon-maskable-512.png",
  "icons/icon.ico",
  "index.html",
  "js/anim.js",
  "js/camera.js",
  "js/combat.js",
  "js/hero.js",
  "js/input.js",
  "js/main.js",
  "js/missions.js",
  "js/npcs.js",
  "js/present.js",
  "js/props.js",
  "js/save.js",
  "js/sprites.js",
  "js/title.js",
  "js/world.js",
  "manifest.webmanifest"
];
// Code/markup: network-first (updates arrive immediately when online). Art/other: stale-while-revalidate.
const NETWORK_FIRST_RE = /(\/|\.html|\.js|\.mjs|\.css|\.webmanifest|\.json)$/i;
const NETWORK_TIMEOUT_MS = 4000;

self.addEventListener('install', (event) => {
  self.skipWaiting(); // not awaited: Chrome resolves it only after activation (would deadlock install)
  event.waitUntil((async () => {
    const cache = await caches.open(CACHE);
    // Add files one by one so a single missing/renamed file can't break the whole install.
    const results = await Promise.allSettled(PRECACHE.map(async (u) => {
      const res = await fetch(new Request(u, { cache: 'reload' }));
      if (!res.ok) throw new Error(u + ' -> HTTP ' + res.status);
      await cache.put(u, res);
    }));
    const failed = results.filter((r) => r.status === 'rejected');
    if (failed.length) console.warn('[sw] ' + failed.length + ' precache file(s) skipped; re-run tools/build-app.mjs', failed.map((r) => String(r.reason)));
  })());
});

self.addEventListener('activate', (event) => {
  event.waitUntil((async () => {
    const keys = await caches.keys();
    await Promise.all(keys.filter((k) => k.startsWith(CACHE_PREFIX) && k !== CACHE).map((k) => caches.delete(k)));
    await self.clients.claim();
  })());
});

self.addEventListener('message', (event) => {
  if (event.data === 'SKIP_WAITING') self.skipWaiting();
  if (event.data === 'GET_VERSION' && event.source) event.source.postMessage({ type: 'SCD_SW_VERSION', version: VERSION });
});

async function fromCache(request) {
  const cache = await caches.open(CACHE);
  return (await cache.match(request, { ignoreSearch: true }))
    || (request.mode === 'navigate' ? cache.match('index.html') : undefined);
}

async function putInCache(request, response) {
  if (response && response.ok && response.type === 'basic') {
    const cache = await caches.open(CACHE);
    await cache.put(request, response.clone());
  }
  return response;
}

async function networkFirst(request) {
  try {
    const net = fetch(request, { cache: 'no-cache' }).then((r) => putInCache(request, r)); // revalidate past the HTTP cache
    const timeout = new Promise((_, rej) => setTimeout(() => rej(new Error('timeout')), NETWORK_TIMEOUT_MS));
    return await Promise.race([net, timeout]);
  } catch (_) {
    const cached = await fromCache(request);
    if (cached) return cached;
    return fetch(request); // last try (surfaces the real network error)
  }
}

async function staleWhileRevalidate(event) {
  const request = event.request;
  const cached = await fromCache(request);
  const refresh = fetch(request, { cache: 'no-cache' }).then((r) => putInCache(request, r)).catch(() => undefined);
  if (cached) { event.waitUntil(refresh); return cached; }
  return (await refresh) || fetch(request);
}

self.addEventListener('fetch', (event) => {
  const { request } = event;
  if (request.method !== 'GET') return;
  const url = new URL(request.url);
  if (url.origin !== self.location.origin) return;
  if (request.mode === 'navigate' || NETWORK_FIRST_RE.test(url.pathname)) {
    event.respondWith(networkFirst(request));
  } else {
    event.respondWith(staleWhileRevalidate(event));
  }
});
